apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: dev
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: prod
    managed-by: argocd
