apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager-prod-green
  namespace: argocd
  labels:
    environment: prod
    slot: green
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/tkrmandar/devops-k8s-manifests.git
    targetRevision: HEAD
    path: prod/green            # only watch prod/green folder

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
