apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager-prod-ingress
  namespace: argocd
  labels:
    environment: prod
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/tkrmandar/devops-k8s-manifests.git
    targetRevision: HEAD
    path: prod                  # watches prod/ folder for ingress.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
